export const GRANT_CLIENT_ACCESS = 'GRANT_CLIENT_ACCESS'
export const CALL_SMART_CONTRACT = 'CALL_SMART_CONTRACT'
export const SEND_SMART_CONTRACT = 'SEND_SMART_CONTRACT'
export const SIGN_TOPIC_AND_MESSAGE = 'SIGN_TOPIC_AND_MESSAGE'