export const CALL_FUNCTION = "CALL_FUNCTION"
export const FUNCTION_CALLED = "FUNCTION_CALLED"
export const REFRESH_OPERATION = "REFRESH_OPERATION"
export const RESET_CONTENT_ACTIONS = "RESET_CONTENT_ACTIONS"